server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/YoungDriverOfTech/cloud-native-config-client.git
          searchPaths: config
          username: # username
          password: # password
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/